# Generated by Django 3.2.16 on 2022-11-03 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='process',
            name='language',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='process',
            name='process_id',
            field=models.TextField(blank=True, default='1a111aa9-6de3-4225-8f49-581e7df9dc8f', null=True),
        ),
    ]
